module.exports = {
  onBoarding: {
    LOGIN_SUCCESS: "Login successfully.",
    CURRENT_PASSWORD: "Current password is wrong",
    PASSWORD_CHANGED: "Password changed successfully.",
    WRONG_PASSWORD: "Password is wrong!",
    USERNAME_INACTIVE: "Account is not active. Please contact to admin.",
    USERNAME_DELETED: "Account is deleted. Please contact to admin",
    PAYLOAD_MISSING: "Payload missing.",
    ACCOUNT_NOT_FOUND: "Account not found.",
    DOCUMENT_NOT_FOUND: "Document not found.",
    RESEND_VERIFICATION_CODE_SENT: "Please check your email for otp.",
    WRONG_VERIFICATION_CODE: "Verification code is incorrect.",
    LINK_EXPIRED: "Please try again with resend email.",
    PASSWORD_RESET: "Password reset successfully.",
    EMAIL_EXIST: "Email already exist.",
    NEW_EMAIL_EXIST: "New email already exist.",
    STATUS_CHANGED: "Status changed successfully",
    USER_DELETED: "User deleted successfully.",
    EMAIL_REQUIRED: "Email required.",
    USER_ID_REQUIRED: "User Id required",
    PASSWORD_REQUIRED: "Password required",
    ONLY_USER_LOGIN: "Invalid credentials",
    PROFILE_UPDATED: "Profile updated successfully.",
    PROFILE_DELETED: "Profile deleted successfully.",
    USER_ADDED: "User added successfully.",
    DOC_ADDED: "Document added successfully.",
    TOKEN_VALID: "This token will valid for 10 hours only.",
    INVALID_ID: "Invalid id.",
    NOT_VERIFIED: "Please verify your email first.",
    EMAIL_AVAILABLE: "You can use this email.",
    EMAIL_TAKEN: "Email is already in use.",
    OTP_MATCHED: "OTP matched successfully",
    INVALID_OTP: "OTP not matched",
    OTP_SENT: "OTP sent successfully",
    ID_REQUIRED: "Id required",
    OTP_REQUIRED: "Verification code required",
    TWO_FACTOR_SUCCESS: "Two factor authentication enabled successfully.",
    LOGIN_LINK_SENT: "Login link sent to partner successfully.",
    USER_INVITED: "User invited successfully.",
    SUCCESSFULLY_REGISTERED: "User successfully registered",
    USERNAME_VERIFIED: "Please verify your email first",
    NO_USER_EXIST: "No user exist with these credentials",
    INVALID_ADDRESS: "Address id invalid",
    USER_ACTIVATE: "User activated successfully",
    NOT_VALID: "You are not authorized user for this portal.",
    INVALID_CREDENTIAL: "Invalid credentials.",
    DUMMY_ID: "666abbecdf0e68f5e9d28a99",
    ALREADY_EXITS: "Email already exist in the application.",
    DATA_NOT_FOUND: "Data not found",
    DATA_RETRIVED_SUCCESSFULLY: "Data retrieved successfully",
    ALREADY_EXITS_DOC: "Document already exist in the application.",
    DOCUMENT_UPDATED: "Document updated successfully.",
    DOCUMENT_ACTIVATED: "Document activated successfully.",
    DOCUMENT_DEACTIVATED: "Document deactivated successfully.",
    DOCUMENT_DELETED: "Document deleted successfully.",
    USER_EXIST: "User already exist",
    LOGOUT: "User logout successfully",
  },

  USER: {
    GROUP_JOINED: "Group joined successfully",
    RECENT_CHAT_FETCHED: "Recents chat fetched successfully",
    USER_ID_REQUIRED: "User ID is required",
    UNREAD_COUNT_FETCHED: "Unread count fetched successfully",
    NOT_FOUND: "User not found",
    CANNOT_DELETE: "Cannot delete venue it is associated with events",
  },

  STAFF: {
    STAFF_ADDED: "Staff added successfully",
    DETAILS: "Staff details fetched successfully",
    NOT_EXIST: "Staff not exist",
  },

  AGENCY: {
    AGENCY_ADDED: "Agency added successfully",
    DETAILS: "Agency details fetched successfully",
    NOT_EXIST: "Agency not exist",
    NOT_FOUND: "Agency not found",
    AGENCY_DELETED: "Agency deleted successfully.",
  },

  category: {
    ALREADY_EXIST: "Category already exist.",
    CREATED: "Category created successfully.",
    UPDATED: "Category updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Category deleted successfully.",
    ASSOCAITED_WITH_FEATURE:
      "Unable to delete category as assocciated with features.",
    ORDER_UPDATED: "Category order updated Successfully.",
  },

  COMMON: {
    SUCCESS: "Success",
    INVALID_COUNTRY_CODE: "Invalid country code",
    SERVER_ERROR: "Something Went Wrong. Please try again.",
    UNAUTHORIZED: "You are not authorized to perform this operation",
    STATUS_CHANGED: "Status Change Successfully",
    NOT_VALID_FILE: "Invalid File Type",
    ID_REQUIRED: "Id required",
    INVALID_ID: "Invalid Id",
    UNSUPPORTED_API_VERSION: "You are using unsupported version of API",
    API_NOT_EXIST: "This API no longer exists",
    INVALID_COORDINATES: "Invalid coordinates",
    SMTP_NOT_FOUND: "Smtp not found",
    MODEL_NAME_REQUIRED: "Model name required",
    UNPROCESSABLE_DATA: "Unprocessable data",
    PAYLOAD_MISSING: "Payload  missing.",
  },

  roles: {
    ALREADY_EXIST: "Roles already exist.",
    CREATED: "Roles created successfully.",
    ID_MISSING: "Id required.",
    UPDATED: "Roles updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Roles deleted successfully.",
  },
  Services: {
    ALREADY_EXIST: "Service already exist.",
    CREATED: "Service created successfully.",
    UPDATED: "Service updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Service deleted successfully.",
  },
  PLAN: {
    ALREADY_EXIST: "Plan already exist.",
    CREATED: "Plan created successfully.",
    UPDATED: "Plan updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Plan deleted successfully.",
    NOT_FOUND: "Plan not found.",
  },

  CATEGORY: {
    ALREADY_EXIST: "Category already exist.",
    CREATED: "Category created successfully.",
    UPDATED: "Category updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Category deleted successfully.",
    ASSOCAITED_WITH_FEATURE:
      "Unable to delete category as assocciated with features.",
    ORDER_UPDATED: "Category order updated Successfully.",
    NOT_FOUND: "Category not found.",
    CANNOT_DELETE: "Cannot delete this category it is associated with events.",
  },

  CATEGORYTYPE: {
    ALREADY_EXIST: "Category type already exist.",
    CREATED: "Category type created successfully.",
    UPDATED: "Category type updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Category type deleted successfully.",
    ASSOCAITED_WITH_FEATURE:
      "Unable to delete category type as assocciated with features.",
    ORDER_UPDATED: "Category order updated Successfully.",
    NOT_FOUND: "Category type not found.",
    CANNOT_DELETE:
      "Cannot delete this category type it is associated with category.",
  },

  AMENITIES: {
    PAYLOAD_MISSING: "Payload missing",
    ALREADY_EXIST: "Amenity already exist.",
    CREATED: "Amenity created successfully.",
    UPDATED: "Amenity updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Amenity deleted successfully.",
    NOT_FOUND: "Amenity not found.",
    NOT_EXIST: "Amenity not found.",
    ID_MISSING: "Id required.",
  },

  FEATURE: {
    PAYLOAD_MISSING: "Payload missing",
    ALREADY_EXIST: "Feature already exist.",
    CREATED: "Feature created successfully.",
    UPDATED: "Feature updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Feature deleted successfully.",
    NOT_FOUND: "Feature not found.",
    NOT_EXIST: "Feature not found.",
    ID_MISSING: "Id required.",
    RETRIEVED: "Feature retrieved successfully",
    ERROR_IN_CREATING: "Error in creating feature",
  },
  BLOG: {
    PAYLOAD_MISSING: "Payload missing",
    ALREADY_EXIST: "BLOG already exist.",
    CREATED: "BLOG created successfully.",
    UPDATED: "BLOG updated successfully.",
    ID_MISSING: "Id required.",
    RETRIEVED: "Blogs retrieved successfully.",
    NOT_FOUND: "Blogs not found.",
    TITLE_EXIST: "Title already exist.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Blog deleted successfully.",
  },
  FOLLOW_UNFOLLOW: {
    PAYLOAD_MISSING: "Payload missing",
    ALREADY_EXIST: "Data already exist.",
    CREATED: "Data created successfully.",
    UPDATED: "Data updated successfully.",
    ID_MISSING: "Id required.",
    RETRIEVED: "Data retrieved successfully.",
    NOT_FOUND: "Data not found.",
    TITLE_EXIST: "Title already exist.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Data deleted successfully.",
  },
  BUDGET: {
    PAYLOAD_MISSING: "Payload missing",
    ALREADY_EXIST: "Budget already exist.",
    CREATED: "Budget created successfully.",
    UPDATED: "Budget updated successfully.",
    ID_MISSING: "Id required.",
    RETRIEVED: "Budget retrieved successfully.",
    NOT_FOUND: "Budget not found.",
    TITLE_EXIST: "Title already exist.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Budget deleted successfully.",
  },
  FAQ: {
    PAYLOAD_MISSING: "Payload missing",
    ALREADY_EXIST: "BLOG already exist.",
    CREATED: "FAQ created successfully.",
    UPDATED: "FAQ updated successfully.",
    ID_MISSING: "Id required.",
    RETRIEVED: "FAQ retrieved successfully.",
    NOT_FOUND: "FAQ not found.",
    QUESTION_EXIST: "Question already exist.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "FAQ deleted successfully.",
  },
  FAVORITE: {
    PAYLOAD_MISSING: "Payload missing",
    ALREADY_EXIST: "Data already exist.",
    CREATED: "Data created successfully.",
    UPDATED: "Data updated successfully.",
    ID_MISSING: "Id required.",
    RETRIEVED: "Data retrieved successfully.",
    NOT_FOUND: "Data not found.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Data deleted successfully.",
  },
  CONTENT_MANAGEMENT: {
    ALREADY_EXIST: "Content already exist.",
    CREATED: "Content created successfully.",
    UPDATED: "Content updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Content deleted successfully.",
    FOUND_SUCCESS: "Content found successfully",
  },
  PROPERTY: {
    CREATED: "Property added successfully",
    ID_MISSING: "Id required.",
    RETRIEVED: "Listing retrieved successfully",
    STATUS_CHANGED: "Status changed successfully.",
    NOT_FOUND: "Property not found.",
    DELETED: "Property deleted successfully.",
    UPDATED: "Property updated successfully.",
    FEATURED: "Property featured successfully",
    UNFEATURED: "Property unfeatured successfully",
    LIKED: "Property like successfully",
    UN_LIKED: "Property unlike successfully",
    FOLLOW: "Property follow successfully",
    UNFOLLOW: "Property unfollow successfully",
  },
  CARD: {
    USER_ID_REQUIRED: "User ID is required",
    INVALID_USER_ID: "Invalid User ID",
    UNABLE_TO_CREATE_STRIPE_CUSTOMER: "Unable to create stripe customer",
    UNABLE_TO_CREATE_CUSTOMER_SOURCE: "Unable to create customer source",
    ADDED: "Card added successfully",
    FETCHED: "Card fetched successfully",
    FETCHED_ALL: "Cards fetched successfully",
    ID_REQUIRED: "Id is required",
    CANT_DELETE_PRIMARY_CARD: "Can't delete primary card",
    DELETED: "Card removed successfully",
    ID_REQUIRED: "Id is required",
    INVALID_ID: "Invalid id",
    USER_NOT_FOUND: "User not found",
    UNAUTHORIZED: "User is not authorized",
    PRIMARY_SET: "Card set as primary card successfully",
    CARD_EXIST: "Card already exists",
    UNABLE_TO_CREATE_BRAINTREE_CUSTOMER: "Unable to create customer"
  },
  DRAFTPROPERTY: {
    PAYLOAD_MISSING: "Payload missing.",
    CREATED: "Property saved in drafts.",
    DELTED: "Property removed from drafts.",
    DATA_FETCH: "User drafts fetched.",
    CANNOTSAVE: "Cannot save this as draft.",
    NOT_FOUND: "Draft not found."
  },
  SCHOOL: {
    EXISTS: "School with these specification already exists.",
    ADDED: "New school successfully added.",
    DELETED: "School deleted successfully.",
    ID_REQ: "Id is required.",
    NOT_EXISTS: "School either doesn't exists or has been deleted."
  }
};
