
const baseUnprotectedRoutes = [
    "/buildingPermits/listing",
    "/user/pro/listing",
    "/service/list",
    "/transaction/list",
    "/peerCampaign/analytics",
    "/funnelUrl/getAll",
    "/form/detail",
    "/form/listing",
    "/form/blog-form",
    "/blogCategories/list",
    "/blogCategories/subCategory/list",
    "/peerCampaign/webhook",
    "/contactTeam/addNew",
    "/contactTeam/detail",
    "/payment/webhook",
    "/plan/listing",
    "/quicksearch/list",
    "/user/checkAccount",
    "/user/emiision-detail",
    "/property/detail",
    "/savesearch/list",
    "/faqs/listing",
    "/user/admin/login",
    "/user/admin/forgot/password",
    "/user/admin/reset/password",
    "/user/reset/user-password",
    "/user/authentication",
    "/user/login",
    "/user/registerUser",
    "/user/auto/login",
    "/user/forgot/password",
    "/user/check/email",
    "/user/verify-email",
    "/user/verify-otp",
    "/upload/document",
    "/upload/image",
    "/upload/multiple-images",
    "/upload/video",
    "/upload/audio",
    "/user/resend-otp",
    "/user/google/signup/login",
    "/category/listing",
    "/user/verify/forgot-otp",
    "/users/verify",
    "/users/forgot-password",
    "/users/login",
    "/users/reset/password",
    "/amenity/listing",
    "/event/get-all-events",
    "/event/get-events-detail",
    "/event/upcoming",
    "/event/detail",
    "/event/like",
    "/event/follow",
    "/event/similar",
    "/users/forgot/password",
    "/users/login",
    "/users/register",
    "/amenity/detail",
    "/amenity/listing",
    "/category/listing",
    "/category/detail",
    "/users/detail",
    "/users/listing",
    "/event/listing",
    "/event/list/venueId",
    "/event/listingByUserId",
    "/user/listing",
    "/users/claim/request",
    "/users/send/credential",
    "/users/claim/venue/listing",
    "/users/claim/venue/detail",
    "/user/auto/login",
    "/user/verifyOtp",
    "/property/listing",
    "/property/detail",
    "/revenue/listing",
    "/blogs/listing",
    "/blogs/detail",
    "/form/looking-for-dream-home",
    "/form/want-to-sell",
    "/user/auto/loginbyid",
    "/support/add",
    "/support/list",
    "/support/delete",
    "/user/delete-by-credentials"
];

const devOnlyDashboardRoutes = [
  "/dashboard/overview",
  "/api/dashboard/overview",
  "/dashboard/activity",
  "/api/dashboard/activity",
];

const unprotectedroutes =
  process.env.NODE_ENV === "production"
    ? baseUnprotectedRoutes
    : [...baseUnprotectedRoutes, ...devOnlyDashboardRoutes];

module.exports = {
  unprotectedroutes,
};
