const dbConfig = require("../config/db.config.js");

const mongoose = require("mongoose");
mongoose.Promise = global.Promise;

const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;

db.users = require("./users.model.js")(mongoose);
db.plans = require("./plans.model.js")(mongoose);
db.categories = require("./categories.model.js")(mongoose);
db.categoryType = require("./categoryType.model.js")(mongoose);
db.amenities = require("./amenities.model.js")(mongoose);
db.events = require("./event.model.js")(mongoose);
db.features = require("./features.model.js")(mongoose);
db.likenfollow = require("./likefollow.model.js")(mongoose);
db.blogs = require("./blogs.model.js")(mongoose);
db.faqs = require("./faq.models.js")(mongoose);
db.content = require("./contentManagement.model.js")(mongoose);
db.property = require("./property.models.js")(mongoose);
db.favorites = require("./favoriteProperty.model.js")(mongoose);
db.followUnfollow = require("./followUnfollow.model.js")(mongoose);
db.notifications = require("./notifications.model.js")(mongoose);
db.revenue = require("./revenueManagement.js")(mongoose);
db.folder = require("./folder.model.js")(mongoose);
db.contactUs = require("./contactUs.model.js")(mongoose);
db.services = require("./services.model.js")(mongoose);
db.devices = require("./device.model.js")(mongoose);
db.setting = require("./setting.model.js")(mongoose);
db.rooms = require("./rooms.model.js")(mongoose);
db.roommembers = require("./roommembers.model.js")(mongoose);
db.messages = require("./messages.model.js")(mongoose);
db.chatcommonoperations = require("./chatcommonoperations.model.js")(mongoose);
db.location = require("./location.model.js")(mongoose);
db.alerts = require("./alerts.model.js")(mongoose);
db.pastTransaction = require("./pastTransactions.model.js")(mongoose);
db.timeline = require("./timeline.model.js")(mongoose);
db.savesearch = require("./savesearch.model.js")(mongoose);
db.quickSearch = require("./quickSearch.model.js")(mongoose)
db.reports = require("./reports.model.js")(mongoose)
db.payments = require("./payments.model.js")(mongoose)
db.subscription = require("./subscription.model.js")(mongoose)
db.cards = require("./cards.model.js")(mongoose)
db.interests = require("./interests.model.js")(mongoose)
db.sessions = require("./sessions.model.js")(mongoose)
db.blockedUsers = require("./blockedUsers.model.js")(mongoose)
db.propertyTransfers = require("./propertyTransfers.model.js")(mongoose)
db.interestTransactions = require("./interestTransactions.model.js")(mongoose)
db.reviews = require("./reviews.model.js")(mongoose)
db.buildingPermits = require("./buildingPermit.model.js")(mongoose)
db.draftProperty = require ("./draftProperty.model.js")(mongoose)
db.schools = require("./schools.model.js")(mongoose)
db.funnelUrl = require("./funnelUrl.model.js")(mongoose)
db.funnelVideoLike = require("./funnelVideoLike.model.js")(mongoose)
db.tags = require("./tags.model.js")(mongoose)
db.contactTeam = require("./contactTeam.model.js")(mongoose)
db.peerEstimation = require("./peerEstimation.model.js")(mongoose)
db.peerCampaign = require("./peerCampaign.model.js")(mongoose)
db.campaignRefPrice = require("./campaignRefPrice.model.js")(mongoose)
db.campaignPayments = require("./campaignPayments.model.js")(mongoose)
db.recentLogs = require("./recentLogs.model.js")(mongoose)
db.blogCategories = require("./blogCategories.model.js")(mongoose)
db.blogSubCategories = require("./blogSubCategories.model.js")(mongoose)
db.form = require("./form.model.js")(mongoose)
db.presetSearches = require("./presetSearches.model.js")(mongoose)
db.agencyReviews = require("./agencyReviews.model.js")(mongoose)
db.adminSettings = require("./adminSettings.model.js")(mongoose)
db.supports = require("./support.model.js")(mongoose)
db.claimOwnerships = require("./claimOwnerships.model.js")(mongoose)


module.exports = db;
